from fpdf import FPDF
from datetime import datetime
from pathlib import Path


class AuditReporter:
    def __init__(self, output_dir):
        self.output_dir = Path(output_dir)
        self.font_dir = Path("assets/fonts")

    def generate_pdf_mom(self, source_title, content, user="Natalia"):
        # Natalia: We use fpdf2 for native UTF-8 support
        pdf = FPDF()
        pdf.add_page()

        # Define font paths
        dejavu_reg = self.font_dir / "DejaVuSans.ttf"
        dejavu_bold = self.font_dir / "DejaVuSans-Bold.ttf"
        korean_reg = self.font_dir / "NotoSansKR-Regular.ttf"

        # Detect Korean characters to switch font automatically
        has_korean = any('\uac00' <= char <= '\ud7a3' for char in content)

        if has_korean and korean_reg.exists():
            pdf.add_font("NotoSans", "", str(korean_reg))
            font_main = "NotoSans"
        elif dejavu_reg.exists():
            pdf.add_font("DejaVu", "", str(dejavu_reg))
            pdf.add_font("DejaVu", "B", str(dejavu_bold))
            font_main = "DejaVu"
        else:
            font_main = "Arial"  # Minimal fallback

        # --- Header ---
        pdf.set_font(font_main, 'B', 16)
        pdf.cell(0, 10, f"Minutes of Meeting: {source_title}", ln=True, align='C')

        pdf.set_font(font_main, '', 10)
        pdf.cell(0, 10, f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True)
        pdf.cell(0, 10, f"Generated by: {user}", ln=True)
        pdf.line(10, 35, 200, 35)
        pdf.ln(10)

        # --- Content ---
        pdf.set_font(font_main, '', 11)
        # multi_cell automatically handles wrapping and Unicode glyphs
        pdf.multi_cell(0, 7, content)

        file_name = f"MoM_{source_title.replace(' ', '_')}_{datetime.now().strftime('%H%M%S')}.pdf"
        file_path = self.output_dir / file_name
        pdf.output(str(file_path))
        return file_path