"""
Translation dictionary for Lumina UI.
Provides localized strings for English, Russian, and Polish.
"""

LANG_DICT = {
    "EN": {
        "title": "Lumina",
        "sidebar_header": "⚙️ Management",
        "option": "Method:",
        "run_btn": "🚀 Process",
        "chat_header": "💬 Chat",
        "chat_placeholder": "Ask a question about the audit...",
        "trans_header": "📄 Transcript",
        "wait_msg": "👈 Please add a source to begin.",
        "quality_option": "Model Quality:",
        "mom_btn": "Meeting Minutes",
        "audit_btn": "Sentiment Analysis",
        "export_btn": "📥 Export PDF",
        "del_btn": "Delete Source",
        "drafts_header": "📝 Drafts",
        "save_btn": "Save Draft",
        "open_btn": "📂 Open",
        "source_select": "📚 Sources:",
        "no_drafts": "No drafts found.",
        "choose_source": "Choose audit sources",
        "method_file": "File Upload",
        "method_mic": "Microphone",
        "quality_fast": "Fast (base)",
        "quality_high": "High Quality (medium)",
        "mic_warning": "🎤 Microphone mode: Recording starts after clicking the button.",
        "file_label": "Upload Audio/Video File:",
        "rec_duration": "Recording duration (sec):",
        "visual_toggle": "Enable AI Vision Analysis",
        "editor_title": "🖋️ Draft Editor",
        "save_success": "Draft saved successfully!",
        "pdf_success": "PDF generated successfully!"
    },
    "RU": {
        "title": "Lumina",
        "sidebar_header": "⚙️ Управление",
        "option": "Метод:",
        "run_btn": "🚀 Обработать",
        "chat_header": "💬 Чат",
        "chat_placeholder": "Задайте вопрос по аудиту...",
        "trans_header": "📄 Транскрипт",
        "wait_msg": "👈 Пожалуйста, добавьте источник.",
        "quality_option": "Качество модели:",
        "mom_btn": "Протокол совещания",
        "audit_btn": "Анализ тональности",
        "export_btn": "📥 Экsporт PDF",
        "del_btn": "Удалить источник",
        "drafts_header": "📝 Черновики",
        "save_btn": "Сохранить",
        "open_btn": "📂 Открыть",
        "source_select": "📚 Источники:",
        "no_drafts": "Черновики не найдены.",
        "choose_source": "Выберите источники",
        "method_file": "Файл",
        "method_mic": "Микрофон",
        "quality_fast": "Быстрый (base)",
        "quality_high": "Высокое качество (medium)",
        "mic_warning": "🎤 Режим микрофона: запись начнется после нажатия кнопки.",
        "file_label": "Загрузить файл:",
        "rec_duration": "Длительность записи (сек):",
        "visual_toggle": "Включить AI Vision",
        "editor_title": "🖋️ Редактор черновика",
        "save_success": "Черновик успешно сохранен!",
        "pdf_success": "PDF успешно сформирован!"
    },
    "PL": {
        "title": "Lumina",
        "sidebar_header": "⚙️ Zarządzanie",
        "option": "Metoda:",
        "run_btn": "🚀 Przetwórz",
        "chat_header": "💬 Czat",
        "chat_placeholder": "Zadaj pytanie dotyczące audytu...",
        "trans_header": "📄 Transkrypcja",
        "wait_msg": "👈 Dodaj źródło, aby rozpocząć.",
        "quality_option": "Jakość modelu:",
        "mom_btn": "Minutki ze spotkania",
        "audit_btn": "Analiza sentymentu",
        "export_btn": "📥 Eksport PDF",
        "del_btn": "Usuń źródło",
        "drafts_header": "📝 Szkice",
        "save_btn": "Zapisz szkic",
        "open_btn": "📂 Otwórz",
        "source_select": "📚 Źródła:",
        "no_drafts": "Nie znaleziono szkiców.",
        "choose_source": "Wybierz źródła audytu",
        "method_file": "Plik",
        "method_mic": "Mikrofon",
        "quality_fast": "Szybki (base)",
        "quality_high": "Wysoka jakość (medium)",
        "mic_warning": "🎤 Tryb mikrofonu: Nagrywanie rozpocznie się po kliknięciu przycisku.",
        "file_label": "Wgraj plik:",
        "rec_duration": "Czas nagrania (sekundy):",
        "visual_toggle": "Włącz analizę AI Vision",
        "editor_title": "🖋️ Edytor szkicu",
        "save_success": "Szkic został zapisany!",
        "pdf_success": "Plik PDF został wygenerowany!"
    }
}