LANG_DICT = {
    "EN": {
        "sidebar_header": "⚙️ Management",
        "source_select": "📚 Library / Sources:",
        "delete_btn": "Remove Source",
        "drafts_header": "📁 Saved Drafts",
        "select_draft": "Choose a draft:",
        "load_draft": "📂 Load",
        "delete_draft_btn": "Delete Draft",
        "run_btn": "🚀 Process",
        "option": "Upload Source via:",
        "method_file": "Upload File",
        "method_mic": "Use Microphone",
        "visual_toggle": "Enable Visual AI",
        "chat_header": "💬 AI Assistant",
        "chat_placeholder": "Ask anything about the content...",
        "chat_error_no_source": "⚠️ No context. Please select a source first.",
        "mom_btn": "Summary / Notes",
        "audit_btn": "Key Insights",
        "zip_btn": "Download ZIP",
        "trans_header": "📄 Transcript",
        "toggle_original": "Show Original",
        "wait_msg": "👈 Add a source to get started.",
        "editor_header": "📝 Report & Notes Editor",
        "draft_filename": "Document Name:",
        "content_label": "Content:",
        "save_draft_btn": "💾 Save Draft",
        "gen_pdf_btn": "📄 Generate PDF",
        "download_pdf_btn": "⬇️ Download PDF",
        "pdf_success": "PDF generated successfully!",
        "save_success": "Draft saved.",
        "quality_option": "Model Quality:",
        "quality_fast": "Fast",
        "quality_high": "High",
        "file_label": "Upload File:",
        "rec_duration": "Recording Time (sec):",
        "mic_warning": "🎤 Recording starts when processing begins."
    },
    "RU": {
        "sidebar_header": "⚙️ Управление",
        "source_select": "📚 Библиотека / Источники:",
        "delete_btn": "Удалить источник",
        "drafts_header": "📁 Черновики",
        "select_draft": "Выберите черновик:",
        "load_draft": "📂 Загрузить",
        "delete_draft_btn": "Удалить",
        "run_btn": "🚀 Запустить",
        "option": "Выберите источник:",
        "method_file": "Загрузить файл",
        "method_mic": "Микрофон",
        "visual_toggle": "Включить визуальный AI",
        "chat_header": "💬 AI Ассистент",
        "chat_placeholder": "Задайте вопрос по содержимому...",
        "chat_error_no_source": "⚠️ Контекст отсутствует. Сначала выберите источник.",
        "mom_btn": "Сводка / Заметки",
        "audit_btn": "Основные выводы",
        "zip_btn": "Скачать ZIP",
        "trans_header": "📄 Транскрипт",
        "toggle_original": "Показать оригинал",
        "wait_msg": "👈 Добавьте источник, чтобы начать.",
        "editor_header": "📝 Редактор отчетов и заметок",
        "draft_filename": "Название документа:",
        "content_label": "Содержание:",
        "save_draft_btn": "💾 Сохранить черновик",
        "gen_pdf_btn": "📄 Создать PDF",
        "download_pdf_btn": "⬇️ Скачать PDF",
        "pdf_success": "PDF успешно создан!",
        "save_success": "Черновик сохранён.",
        "quality_option": "Качество модели:",
        "quality_fast": "Быстрое",
        "quality_high": "Высокое",
        "file_label": "Загрузить файл:",
        "rec_duration": "Время записи (сек):",
        "mic_warning": "🎤 Запись начнется после запуска обработки."
    },
    "PL": {
        "sidebar_header": "⚙️ Zarządzanie",
        "source_select": "📚 Biblioteka / Źródła:",
        "delete_btn": "Usuń źródło",
        "drafts_header": "📁 Szkice",
        "select_draft": "Wybierz szkic:",
        "load_draft": "📂 Wczytaj",
        "delete_draft_btn": "Usuń",
        "run_btn": "🚀 Przetwórz",
        "option": "Wgraj źródło przez:",
        "method_file": "Prześlij plik",
        "method_mic": "Mikrofon",
        "visual_toggle": "Włącz wizualne AI",
        "chat_header": "💬 Asystent AI",
        "chat_placeholder": "Zadaj pytanie dotyczące treści...",
        "chat_error_no_source": "⚠️ Brak kontekstu. Najpierw wybierz źródło.",
        "mom_btn": "Podsumowanie / Notatki",
        "audit_btn": "Kluczowe wnioski",
        "zip_btn": "Pobierz ZIP",
        "trans_header": "📄 Transkrypcja",
        "toggle_original": "Pokaż oryginał",
        "wait_msg": "👈 Dodaj źródło, aby rozpocząć.",
        "editor_header": "📝 Edytor raportów i notatek",
        "draft_filename": "Nazwa dokumentu:",
        "content_label": "Treść:",
        "save_draft_btn": "💾 Zapisz szkic",
        "gen_pdf_btn": "📄 Generuj PDF",
        "download_pdf_btn": "⬇️ Pobierz PDF",
        "pdf_success": "PDF został wygenerowany!",
        "save_success": "Szkic zapisany.",
        "quality_option": "Jakość modelu:",
        "quality_fast": "Szybka",
        "quality_high": "Wysoka",
        "file_label": "Wgraj plik:",
        "rec_duration": "Czas nagrania (sek.):",
        "mic_warning": "🎤 Nagrywanie rozpocznie się po uruchomieniu przetwarzania."
    }
}
